import {
  Injectable,
  CanActivate,
  ExecutionContext,
  UnauthorizedException,
} from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { FastifyRequest } from 'fastify';
import { SupabaseService } from '../../database/supabase.service';
import { LoggerService } from '../../observability/logger.service';
import { IS_PUBLIC_KEY } from '../decorators/public.decorator';
import { SessionService } from '../../auth/session.service';

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(
    private readonly supabase: SupabaseService,
    private readonly logger: LoggerService,
    private readonly reflector: Reflector,
    private readonly sessionService: SessionService,
  ) { }

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);

    if (isPublic) {
      return true;
    }

    const request = context.switchToHttp().getRequest<FastifyRequest>();
    const authHeader = request.headers.authorization;
    const sessionCookie = request.cookies?.session;

    // 1. Try Session Cookie (generated by our SessionService)
    if (sessionCookie) {
      const sessionUser = this.sessionService.verifySessionToken(sessionCookie);

      if (sessionUser) {
        // Attach the user to the request object
        (request as any).user = {
          id: sessionUser.id,
          email: sessionUser.email,
          metadata: {
            name: sessionUser.name,
            avatar_url: sessionUser.avatar_url,
          },
        };
        return true;
      }
      // If cookie exists but invalid, we could throw or fall through. 
      // Let's log warning and try header (though unlikely to have both)
      this.logger.warn('Invalid session cookie present');
    }

    // 2. Try Authorization Header (Supabase direct token)
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      // If we had no cookie and no header, fail
      if (!sessionCookie) {
        throw new UnauthorizedException('Missing or invalid authorization header');
      }
      // If we had an invalid cookie and no header, fail
      throw new UnauthorizedException('Invalid or expired session');
    }

    const token = authHeader.substring(7);

    try {
      const {
        data: { user },
        error,
      } = await this.supabase.getClient().auth.getUser(token);

      if (error || !user) {
        throw new UnauthorizedException('Invalid or expired token');
      }

      // Attach the user to the request object
      (request as any).user = {
        id: user.id,
        email: user.email,
        metadata: user.user_metadata,
      };

      return true;
    } catch (error) {
      if (error instanceof UnauthorizedException) {
        throw error;
      }

      this.logger.error('Auth guard verification failed', {
        error: error instanceof Error ? error.message : String(error),
      });
      throw new UnauthorizedException('Authentication failed');
    }
  }
}
